// Detects credential additions or modifications to Entra ID apps — a common persistence technique to authenticate without a user account or MFA.

AuditLogs
| where TimeGenerated > ago(30d)
| where OperationName in (
    "Add service principal credentials",
    // "Add service principal",
    "Update application – Certificates and secrets management",
    "Create application – Certificates and secrets management",
    "Update application",
    "Add application"
)
| extend AppName = tostring(TargetResources[0].displayName)
| extend InitiatedByUser = tostring(InitiatedBy.user.userPrincipalName)
| project TimeGenerated, OperationName, AppName, InitiatedByUser
| sort by TimeGenerated desc
